sudo: required

language: python

python:
    - '3.6'

branches:
    only:
        - master
        - issue_40
before_script:
    - chmod +x scripts/run_scripts.sh
    - npm install
    - npm i -g markdown-to-json
    - pip install -r requirements.txt

cache:
    npm: true
    directories:
        - node_modules

script:
    - ./scripts/run_scripts.sh
    - npm install
    - npm run build
    - cat utils/db.json

deploy:
    provider: pages
    local_dir: dist/
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: issue_40
